on: push

jobs:
  validate-dates:
    name: Validate date formats
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate date format in Markdown files
        run: |
          # Find all Markdown files and check their dates
          find . -name "*.md" -exec grep -H -E '^\s*date:\s*(.*)' {} \; | while read -r line; do
            # Extract the date from the line
            date=$(echo "$line" | sed -E 's/.*date:\s*(.*)/\1/')
            
            # Validate the date format using a regular expression
            if ! [[ "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[+-][0-9]{4}$ ]]; then
              echo "Error: Invalid date format in file $line. Expected YYYY-MM-DD HH:MM:SS -TZD format."
              exit 1
            fi
          done

      - name: All dates are valid
        run: echo "All Markdown files have valid date formats."
